import React, {useEffect, useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ShoppingCart, Store, ChefHat, BarChart3, Shield, FileText, Package, Users, Lock, Mail, Code, LayoutDashboard, ClipboardList } from 'lucide-react';
import './style.css';

const API = import.meta.env.VITE_API_URL || '';
const money = (n) => `₹${Number(n||0).toFixed(2)}`;
async function api(path, opts={}){
  const token=localStorage.getItem('ff_token');
  const headers={'Content-Type':'application/json', ...(opts.headers||{})};
  if(token) headers.Authorization=`Bearer ${token}`;
  const res=await fetch(API+path,{...opts, headers});
  if(!res.ok) throw new Error(await res.text());
  return res.json();
}
function Card({children, className=''}){ return <div className={'card '+className}>{children}</div> }
function Pill({children}){ return <span className="pill">{children}</span> }

function Login({onLogin}){
  const [phone,setPhone]=useState('9999999999'); const [name,setName]=useState('Admin User'); const [err,setErr]=useState('');
  async function submit(e){e.preventDefault(); setErr(''); try{const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({phone,name,otp:'123456'})}); localStorage.setItem('ff_token',r.token); onLogin(r.user)}catch(ex){setErr(ex.message)}}
  return <div className="loginShell"><Card className="loginCard"><div className="brandLogo">TF</div><h1>Truflux FoodFlow</h1><p>Unified food ordering, POS, kitchen, inventory and analytics platform.</p><form onSubmit={submit}><label>Mobile Number Login</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Mobile number"/><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name"/><div className="otpNote">Prototype OTP is auto-applied as <b>123456</b>. Login persists using browser local storage.</div><button>Login with OTP</button></form>{err && <p className="err">{err}</p>}</Card></div>
}

function Customer({stores, menu, selectedStore, setSelectedStore, refresh}){
  const [cart,setCart]=useState([]); const [source,setSource]=useState('app'); const [fulfillment,setFulfillment]=useState('pickup'); const [msg,setMsg]=useState('');
  const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
  function add(item){ setCart(c=>{const ex=c.find(x=>x.id===item.id); if(ex) return c.map(x=>x.id===item.id?{...x,qty:x.qty+1}:x); return [...c,{...item,qty:1,customization:''}]}) }
  function qty(id,d){ setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+d)}:x).filter(x=>x.qty>0)) }
  async function place(){ if(!cart.length) return; const payload={store_id:selectedStore,source,fulfillment,payment_method:'UPI',scheduled_for:'Today',items:cart.map(x=>({menu_item_id:x.id,qty:x.qty,customization:x.customization||''}))}; const r=await api('/api/orders',{method:'POST',body:JSON.stringify(payload)}); setMsg(`Order ${r.order_no} placed. Total ${money(r.total)}`); setCart([]); refresh(); }
  return <div className="grid2"><div><Card><div className="row"><h2>Consumer Ordering</h2><Pill>App • Web • Kiosk • POS</Pill></div><div className="toolbar"><select value={selectedStore} onChange={e=>setSelectedStore(Number(e.target.value))}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)}><option>app</option><option>web</option><option>kiosk</option><option>pos</option></select><select value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option>pickup</option><option>delivery</option><option>dine-in</option></select></div></Card><div className="menuGrid">{menu.map(m=><Card key={m.id} className="menuItem"><div className="foodPic">{m.name.includes('Dosa')?'🥞':m.name.includes('Coffee')?'☕':m.name.includes('Rice')?'🍚':m.name.includes('Dal')?'🍛':'🥘'}</div><h3>{m.name}</h3><p>{m.description}</p><div className="row"><b>{money(m.price)}</b><button onClick={()=>add(m)}>Add</button></div></Card>)}</div></div><Card className="cart"><h2>Cart & Payment</h2>{cart.length===0 && <p>No items selected.</p>}{cart.map(x=><div className="cartLine" key={x.id}><div><b>{x.name}</b><small>{money(x.price)} x {x.qty}</small></div><div><button onClick={()=>qty(x.id,-1)}>-</button><button onClick={()=>qty(x.id,1)}>+</button></div></div>)}<div className="total">Total {money(total)}</div><button onClick={place} disabled={!cart.length}>Checkout & Pay</button>{msg && <p className="ok">{msg}</p>}</Card></div>
}
function KDS({orders, refresh}){ const open=orders.filter(o=>['confirmed','preparing'].includes(o.status)); async function upd(o,s){await api(`/api/orders/${o.order_no}/status?status=${s}`,{method:'PATCH'}); refresh()} return <Card><div className="row"><h2>Kitchen Display System</h2><Pill>Live order queue</Pill></div><div className="kdsGrid">{open.map(o=><div className="ticket" key={o.id}><b>{o.order_no}</b><p>{o.store?.name}</p><p>{o.source} • {o.fulfillment} • {money(o.total)}</p><button onClick={()=>upd(o,'preparing')}>Preparing</button><button onClick={()=>upd(o,'ready')}>Ready</button></div>)}{!open.length && <p>No pending kitchen orders.</p>}</div></Card> }
function Inventory({inventory, stores, selectedStore, setSelectedStore, refresh}){ async function receive(r){await api('/api/inventory/update',{method:'POST',body:JSON.stringify({store_id:selectedStore,ingredient_id:r.ingredient_id||r.id,received_qty:10})}); refresh()} return <Card><div className="row"><h2>Inventory & Stock Control</h2><select value={selectedStore} onChange={e=>setSelectedStore(Number(e.target.value))}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><table><thead><tr><th>Material</th><th>Unit</th><th>Consumed</th><th>Wastage</th><th>Closing</th><th>Status</th></tr></thead><tbody>{inventory.map(r=><tr key={r.id}><td>{r.ingredient}</td><td>{r.unit}</td><td>{r.consumed_qty.toFixed(2)}</td><td>{r.wastage_qty.toFixed(2)}</td><td>{r.closing_qty.toFixed(2)}</td><td>{r.low_stock?<span className="bad">Low Stock</span>:<span className="good">OK</span>}</td></tr>)}</tbody></table></Card> }
function Analytics({summary}){ return <div><div className="metrics"><Card><ShoppingCart/><b>{summary.orders}</b><span>Total Orders</span></Card><Card><BarChart3/><b>{money(summary.sales)}</b><span>Sales</span></Card><Card><ChefHat/><b>{summary.pending}</b><span>Kitchen Queue</span></Card><Card><Package/><b>{summary.low_stock}</b><span>Low Stock Items</span></Card></div><div className="grid2"><Card><h2>Source Mix</h2>{(summary.by_source||[]).map(x=><div className="bar" key={x.source}><span>{x.source}</span><b>{x.orders} orders • {money(x.sales)}</b></div>)}</Card><Card><h2>Top Items</h2>{(summary.top_items||[]).map(x=><div className="bar" key={x.name}><span>{x.name}</span><b>{x.qty}</b></div>)}</Card></div></div> }
function Reports(){ const outputs=[['PDF',FileText],['Excel',ClipboardList],['CSV',FileText],['Scheduled Email',Mail],['API Feed',Code],['Dashboard Widget',LayoutDashboard]]; return <Card><div className="row"><h2>Custom Reporting</h2><Pill>Governance ready</Pill></div><div className="outputGrid">{outputs.map(([n,Icon])=><div className="output" key={n}><Icon/><b>{n}</b></div>)}</div><div className="toolbar"><a className="buttonLink" href="/api/reports/custom?format=pdf" target="_blank">Download PDF</a><a className="buttonLink" href="/api/reports/custom?format=csv" target="_blank">Download CSV</a><a className="buttonLink" href="/api/reports/custom?format=json" target="_blank">API Feed</a></div></Card> }
function Admin({logs}){ return <div className="grid2"><Card><h2>POS Monitoring, User Management & Security</h2><div className="adminList"><p><Store/> Store-wise POS health, active terminals and sales.</p><p><Users/> Role-ready users: admin, manager, cashier, kitchen and customer.</p><p><Shield/> Secure session token, OTP login and audit trails.</p><p><Lock/> Production-ready extension points for SSO, RBAC, encryption and payment compliance.</p></div></Card><Card><h2>Audit Logs</h2>{logs.map(l=><div className="log" key={l.id}><b>{l.action}</b><span>{l.actor} • {new Date(l.created_at).toLocaleString()}</span><p>{l.details}</p></div>)}</Card></div> }
function App(){ const [user,setUser]=useState(null); const [tab,setTab]=useState('dashboard'); const [stores,setStores]=useState([]); const [selectedStore,setSelectedStore]=useState(1); const [menu,setMenu]=useState([]); const [orders,setOrders]=useState([]); const [inventory,setInventory]=useState([]); const [summary,setSummary]=useState({}); const [logs,setLogs]=useState([]);
  async function refresh(){ const [st,mu,or,inv,su,lo]=await Promise.all([api('/api/stores'),api(`/api/menu?store_id=${selectedStore}`),api('/api/orders'),api(`/api/inventory?store_id=${selectedStore}`),api('/api/analytics/summary'),api('/api/audit')]); setStores(st); setMenu(mu); setOrders(or); setInventory(inv); setSummary(su); setLogs(lo); }
  useEffect(()=>{ api('/api/auth/me').then(setUser).catch(()=>{}); },[]); useEffect(()=>{ if(user) refresh(); },[user, selectedStore]);
  if(!user) return <Login onLogin={setUser}/>;
  const tabs=[['dashboard','Operations Dashboard'],['ordering','Ordering'],['kds','Kitchen Display'],['inventory','Inventory'],['reports','Reports'],['admin','Admin']];
  return <div><header><div><h1>Truflux FoodFlow</h1><p>Bangalore, Karnataka • Multi-store food retail operations platform</p></div><div className="userBox">{user.name}<button onClick={()=>{localStorage.removeItem('ff_token'); location.reload()}}>Logout</button></div></header><nav>{tabs.map(([id,n])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{n}</button>)}</nav><main>{tab==='dashboard'&&<Analytics summary={summary}/>} {tab==='ordering'&&<Customer stores={stores} menu={menu} selectedStore={selectedStore} setSelectedStore={setSelectedStore} refresh={refresh}/>} {tab==='kds'&&<KDS orders={orders} refresh={refresh}/>} {tab==='inventory'&&<Inventory inventory={inventory} stores={stores} selectedStore={selectedStore} setSelectedStore={setSelectedStore} refresh={refresh}/>} {tab==='reports'&&<Reports/>} {tab==='admin'&&<Admin logs={logs}/>}</main><footer>Truflux Technologies Private Limited © 2026 • FoodFlow v1.0.0</footer></div>
}

createRoot(document.getElementById('root')).render(<App/>);
